# Importing basic Library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Importing dataset : power_actual

In [2]:
df_power_actual = pd.read_csv('power_actual.csv')
print (df_power_actual.shape)
df_power_actual.head(3)

(70080, 5)

   Unnamed: 0             datetime  ghi  gti  power
0           0  2017-10-01 00:00:00  0.0  0.0    0.0
1           1  2017-10-01 00:15:00  0.0  0.0    0.0
2           2  2017-10-01 00:30:00  0.0  0.0    0.0

In [3]:
df_power_actual.tail(3)

       Unnamed: 0             datetime  ghi  gti  power
70077       70077  2019-09-30 23:15:00  0.0  0.0    0.0
70078       70078  2019-09-30 23:30:00  0.0  0.0    0.0
70079       70079  2019-09-30 23:45:00  0.0  0.0    0.0

# Importing dataset : weather_actuals

In [4]:
df_weather_actuals = pd.read_csv('weather_actuals.csv')
print (df_weather_actuals.shape)
df_weather_actuals.head(2)

(13619, 31)

,Unnamed: 0,plant_id,datetime_utc,datetime_local,cloud_cover,apparent_temperature,temperature,humidity,dew_point,wind_bearing,...,precip_accumulation,precip_intensity,precip_probability,precip_type,visibility,sunrise,sunset,icon,summary,updated_at
0,0,1,2017-09-30 18:30:00,2017-10-01 00:00:00,0.0,26.52,26,1,19.46,308,...,-9999.0,-9999.0,-9999.0,rain,3.57,2017-10-01 00:52:02,2017-10-01 12:45:07,clear-night,Clear,2019-07-16 16:37:16
1,1,1,2017-09-30 19:30:00,2017-10-01 01:00:00,0.0,28.78,27,1,20.06,-9999,...,-9999.0,-9999.0,-9999.0,rain,3.06,2017-10-01 00:52:02,2017-10-01 12:45:07,fog,Foggy,2019-07-16 16:37:16

In [5]:
df_weather_actuals.tail(2)

,Unnamed: 0,plant_id,datetime_utc,datetime_local,cloud_cover,apparent_temperature,temperature,humidity,dew_point,wind_bearing,...,precip_accumulation,precip_intensity,precip_probability,precip_type,visibility,sunrise,sunset,icon,summary,updated_at
13617,13617,1,2019-09-30 16:30:00,2019-09-30 22:00:00,0.30,28.97,27,1,21.99,88,...,NaN,0.0,0.0,NaN,16.09,2019-09-30 00:51:16,2019-09-30 12:46:54,partly-cloudy-night,Partly Cloudy,2019-10-01 23:32:46
13618,13618,1,2019-09-30 17:30:00,2019-09-30 23:00:00,0.35,28.15,26,1,22.09,95,...,NaN,0.0,0.0,NaN,16.09,2019-09-30 00:51:16,2019-09-30 12:46:54,partly-cloudy-night,Partly Cloudy,2019-10-01 23:32:46

In [6]:
df_weather_actuals.columns

Index(['Unnamed: 0', 'plant_id', 'datetime_utc', 'datetime_local',
       'cloud_cover', 'apparent_temperature', 'temperature', 'humidity',
       'dew_point', 'wind_bearing', 'wind_speed', 'wind_chill', 'wind_gust',
       'heat_index', 'pressure', 'qpf', 'uv_index', 'snow', 'pop', 'fctcode',
       'ozone', 'precip_accumulation', 'precip_intensity',
       'precip_probability', 'precip_type', 'visibility', 'sunrise', 'sunset',
       'icon', 'summary', 'updated_at'],
      dtype='object')

# Importing dataset for forecasting purpose : weather_forecast

In [7]:
df_weather_forecast = pd.read_csv('weather_forecast.csv')
print (df_weather_forecast.shape)
df_weather_forecast.head(2)

(648, 31)

,Unnamed: 0,plant_id,datetime_utc,datetime_local,cloud_cover,apparent_temperature,temperature,humidity,dew_point,wind_bearing,...,precip_accumulation,precip_intensity,precip_probability,precip_type,visibility,sunrise,sunset,icon,summary,updated_at
0,0,1,2019-09-30 18:30:00,2019-10-01 00:00:00,0.35,26.41,26,1,22.01,101,...,NaN,0.0,0.0,NaN,16.09,2019-10-01 00:51:47,2019-10-01 12:45:42,partly-cloudy-night,Partly Cloudy,2019-10-02 23:32:38
1,1,1,2019-09-30 19:30:00,2019-10-01 01:00:00,0.43,25.95,25,1,22.06,105,...,NaN,0.0,0.0,NaN,16.09,2019-10-01 00:51:47,2019-10-01 12:45:42,partly-cloudy-night,Partly Cloudy,2019-10-02 23:32:38

In [8]:
df_weather_forecast.tail(2)

,Unnamed: 0,plant_id,datetime_utc,datetime_local,cloud_cover,apparent_temperature,temperature,humidity,dew_point,wind_bearing,...,precip_accumulation,precip_intensity,precip_probability,precip_type,visibility,sunrise,sunset,icon,summary,updated_at
646,646,1,2019-10-27 16:30:00,2019-10-27 22:00:00,0.0,22.86,23,1,12.50,92,...,NaN,0.0,0.0,NaN,16.09,2019-10-27 01:07:31,2019-10-27 12:18:06,clear-night,Clear,2019-10-28 12:33:28
647,647,1,2019-10-27 17:30:00,2019-10-27 23:00:00,0.0,22.21,22,1,12.67,146,...,NaN,0.0,0.0,NaN,16.09,2019-10-27 01:07:31,2019-10-27 12:18:06,clear-night,Clear,2019-10-28 12:33:28

In [9]:
df_weather_forecast.columns

Index(['Unnamed: 0', 'plant_id', 'datetime_utc', 'datetime_local',
       'cloud_cover', 'apparent_temperature', 'temperature', 'humidity',
       'dew_point', 'wind_bearing', 'wind_speed', 'wind_chill', 'wind_gust',
       'heat_index', 'pressure', 'qpf', 'uv_index', 'snow', 'pop', 'fctcode',
       'ozone', 'precip_accumulation', 'precip_intensity',
       'precip_probability', 'precip_type', 'visibility', 'sunrise', 'sunset',
       'icon', 'summary', 'updated_at'],
      dtype='object')

# Merging two datasets : power_actual + weather_actuals

In [10]:
df_power_actual = df_power_actual.drop(['Unnamed: 0'],axis=1)

In [11]:
df_power_actual.columns = ['datetime_local', 'ghi', 'gti', 'power']

In [12]:
df =pd.merge(df_power_actual,df_weather_actuals,on='datetime_local')

In [13]:
df.head(3)

,datetime_local,ghi,gti,power,Unnamed: 0,plant_id,datetime_utc,cloud_cover,apparent_temperature,temperature,...,precip_accumulation,precip_intensity,precip_probability,precip_type,visibility,sunrise,sunset,icon,summary,updated_at
0,2017-10-01 00:00:00,0.0,0.0,0.0,0,1,2017-09-30 18:30:00,0.0,26.52,26,...,-9999.0,-9999.0,-9999.0,rain,3.57,2017-10-01 00:52:02,2017-10-01 12:45:07,clear-night,Clear,2019-07-16 16:37:16
1,2017-10-01 01:00:00,0.0,0.0,0.0,1,1,2017-09-30 19:30:00,0.0,28.78,27,...,-9999.0,-9999.0,-9999.0,rain,3.06,2017-10-01 00:52:02,2017-10-01 12:45:07,fog,Foggy,2019-07-16 16:37:16
2,2017-10-01 02:00:00,0.0,0.0,0.0,2,1,2017-09-30 20:30:00,0.0,26.58,26,...,-9999.0,-9999.0,-9999.0,rain,3.06,2017-10-01 00:52:02,2017-10-01 12:45:07,fog,Foggy,2019-07-16 16:37:16

In [14]:
df = df.drop(['Unnamed: 0'],axis=1)
df.head(2)

,datetime_local,ghi,gti,power,plant_id,datetime_utc,cloud_cover,apparent_temperature,temperature,humidity,...,precip_accumulation,precip_intensity,precip_probability,precip_type,visibility,sunrise,sunset,icon,summary,updated_at
0,2017-10-01 00:00:00,0.0,0.0,0.0,1,2017-09-30 18:30:00,0.0,26.52,26,1,...,-9999.0,-9999.0,-9999.0,rain,3.57,2017-10-01 00:52:02,2017-10-01 12:45:07,clear-night,Clear,2019-07-16 16:37:16
1,2017-10-01 01:00:00,0.0,0.0,0.0,1,2017-09-30 19:30:00,0.0,28.78,27,1,...,-9999.0,-9999.0,-9999.0,rain,3.06,2017-10-01 00:52:02,2017-10-01 12:45:07,fog,Foggy,2019-07-16 16:37:16

# Data Summary

In [15]:
df.describe()

,ghi,gti,power,plant_id,cloud_cover,apparent_temperature,temperature,humidity,dew_point,wind_bearing,...,qpf,uv_index,snow,pop,fctcode,ozone,precip_accumulation,precip_intensity,precip_probability,visibility
count,6810.0,6810.0,13619.000000,13619.0,13619.000000,13619.000000,13619.000000,13619.000000,13619.000000,13619.000000,...,3744.0,13619.000000,3744.0,3744.0,3744.0,13619.000000,3744.0,13619.000000,13619.000000,13619.000000
mean,0.0,0.0,35.255627,1.0,-314.005310,25.944639,24.498054,0.537411,11.924626,-498.677363,...,-9999.0,-2394.989280,-9999.0,-9999.0,-9999.0,-2187.730797,-9999.0,-2396.367775,-2396.398081,-117.086149
std,0.0,0.0,557.059759,0.0,1744.610028,10.469808,8.840016,0.498617,9.129459,2557.943872,...,0.0,4269.320576,0.0,0.0,0.0,4385.706548,0.0,4268.545854,4268.528833,1130.763316
min,0.0,0.0,0.000000,1.0,-9999.000000,3.140000,5.000000,0.000000,-20.560000,-9999.000000,...,-9999.0,-9999.000000,-9999.0,-9999.0,-9999.0,-9999.000000,-9999.0,-9999.000000,-9999.000000,-9999.000000
25%,0.0,0.0,0.000000,1.0,0.000000,17.310000,17.000000,0.000000,5.920000,79.000000,...,-9999.0,0.000000,-9999.0,-9999.0,-9999.0,236.900000,-9999.0,0.000000,0.000000,3.540000
50%,0.0,0.0,0.000000,1.0,0.000000,25.540000,25.000000,1.000000,10.710000,149.000000,...,-9999.0,0.000000,-9999.0,-9999.0,-9999.0,270.800000,-9999.0,0.000000,0.000000,16.090000
75%,0.0,0.0,5.810000,1.0,0.410000,34.580000,31.000000,1.000000,19.670000,293.000000,...,-9999.0,2.000000,-9999.0,-9999.0,-9999.0,280.800000,-9999.0,0.000000,0.000000,16.090000
max,0.0,0.0,15504.750000,1.0,1.000000,49.750000,47.000000,1.000000,28.350000,359.000000,...,-9999.0,12.000000,-9999.0,-9999.0,-9999.0,351.700000,-9999.0,6.220000,0.730000,16.090000

In [16]:
df.isnull().sum()

datetime_local             0
ghi                     6809
gti                     6809
power                      0
plant_id                   0
datetime_utc               0
cloud_cover                0
apparent_temperature       0
temperature                0
humidity                   0
dew_point                  0
wind_bearing               0
wind_speed                 0
wind_chill              9875
wind_gust                  0
heat_index              9875
pressure                   0
qpf                     9875
uv_index                   0
snow                    9875
pop                     9875
fctcode                 9875
ozone                      0
precip_accumulation     9875
precip_intensity           0
precip_probability         0
precip_type             7129
visibility                 0
sunrise                    0
sunset                     0
icon                       0
summary                    0
updated_at                 0
dtype: int64

# Filtering numeric data

In [17]:
numeric = []
category = []
for i in df :
    if (df[i].dtypes=='float64' or df[i].dtypes=='int64'):
        numeric.append(i)     
    else :
        category.append(i)

# Checking the min and max value from the data

In [18]:
for i in numeric:
    print (i, "-->",min(df[i]), "-->", max(df[i]))

ghi --> 0.0 --> 0.0
gti --> 0.0 --> 0.0
power --> 0.0 --> 15504.75
plant_id --> 1 --> 1
cloud_cover --> -9999.0 --> 1.0
apparent_temperature --> 3.14 --> 49.75
temperature --> 5 --> 47
humidity --> 0 --> 1
dew_point --> -20.56 --> 28.35
wind_bearing --> -9999 --> 359
wind_speed --> -9999.0 --> 9.73
wind_chill --> -9999.0 --> -9999.0
wind_gust --> -9999.0 --> 15.15
heat_index --> -9999.0 --> -9999.0
pressure --> -9999.0 --> 1025.69
qpf --> -9999.0 --> -9999.0
uv_index --> -9999 --> 12
snow --> -9999.0 --> -9999.0
pop --> -9999.0 --> -9999.0
fctcode --> -9999.0 --> -9999.0
ozone --> -9999.0 --> 351.7
precip_accumulation --> -9999.0 --> -9999.0
precip_intensity --> -9999.0 --> 6.22
precip_probability --> -9999.0 --> 0.73
visibility --> -9999.0 --> 16.09

# Checking the unique values out of the data

In [21]:
print (df.ghi.unique())
print (df.gti.unique())
print (df.plant_id.unique())
print (df.wind_chill.unique())
print (df.heat_index.unique())
print (df.qpf.unique())
print (df.snow.unique())
print (df['pop'].unique())
print (df.fctcode.unique())
print (df.precip_accumulation.unique())
print(df.ozone.unique())

[ 0. nan]
[ 0. nan]
[1]
[-9999.    nan]
[-9999.    nan]
[-9999.    nan]
[-9999.    nan]
[-9999.    nan]
[-9999.    nan]
[-9999.    nan]
[-9999.     335.82   333.09 ...   302.2    303.1    301.6 ]

### Dropping out the columns whoes minimum and maximum values are the same

In [22]:
df_drop_numeric = df.drop(['ghi','gti','plant_id','wind_chill','heat_index','qpf','snow','pop','fctcode','precip_accumulation'],axis=1)
df_drop_numeric.shape

(13619, 23)

In [23]:
df_drop_numeric.head(3)

,datetime_local,power,datetime_utc,cloud_cover,apparent_temperature,temperature,humidity,dew_point,wind_bearing,wind_speed,...,ozone,precip_intensity,precip_probability,precip_type,visibility,sunrise,sunset,icon,summary,updated_at
0,2017-10-01 00:00:00,0.0,2017-09-30 18:30:00,0.0,26.52,26,1,19.46,308,0.83,...,-9999.0,-9999.0,-9999.0,rain,3.57,2017-10-01 00:52:02,2017-10-01 12:45:07,clear-night,Clear,2019-07-16 16:37:16
1,2017-10-01 01:00:00,0.0,2017-09-30 19:30:00,0.0,28.78,27,1,20.06,-9999,-9999.00,...,-9999.0,-9999.0,-9999.0,rain,3.06,2017-10-01 00:52:02,2017-10-01 12:45:07,fog,Foggy,2019-07-16 16:37:16
2,2017-10-01 02:00:00,0.0,2017-09-30 20:30:00,0.0,26.58,26,1,19.97,-9999,-9999.00,...,-9999.0,-9999.0,-9999.0,rain,3.06,2017-10-01 00:52:02,2017-10-01 12:45:07,fog,Foggy,2019-07-16 16:37:16

In [24]:
category

['datetime_local',
 'datetime_utc',
 'precip_type',
 'sunrise',
 'sunset',
 'icon',
 'summary',
 'updated_at']

# Dropping all the date apart from 'datetime_local

In [25]:
df_drop_category = df_drop_numeric.drop([ 'datetime_utc', 'sunrise', 'sunset','updated_at'],axis = 1)
df_drop_category.head(3)

,datetime_local,power,cloud_cover,apparent_temperature,temperature,humidity,dew_point,wind_bearing,wind_speed,wind_gust,pressure,uv_index,ozone,precip_intensity,precip_probability,precip_type,visibility,icon,summary
0,2017-10-01 00:00:00,0.0,0.0,26.52,26,1,19.46,308,0.83,-9999.0,1007.9,-9999,-9999.0,-9999.0,-9999.0,rain,3.57,clear-night,Clear
1,2017-10-01 01:00:00,0.0,0.0,28.78,27,1,20.06,-9999,-9999.00,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,rain,3.06,fog,Foggy
2,2017-10-01 02:00:00,0.0,0.0,26.58,26,1,19.97,-9999,-9999.00,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,rain,3.06,fog,Foggy

In [26]:
df_drop_category.shape

(13619, 19)

# Converting all int64 data type into float64

In [27]:
df1 = df_drop_category.copy()
df1.shape

(13619, 19)

In [28]:
for i in df1 :
    if (df1[i].dtypes=='int64'):
        df1[i] = df1[i].astype(float)

In [29]:
df1.dtypes

datetime_local           object
power                   float64
cloud_cover             float64
apparent_temperature    float64
temperature             float64
humidity                float64
dew_point               float64
wind_bearing            float64
wind_speed              float64
wind_gust               float64
pressure                float64
uv_index                float64
ozone                   float64
precip_intensity        float64
precip_probability      float64
precip_type              object
visibility              float64
icon                     object
summary                  object
dtype: object

# We can see so many values contain -9999.0 values, we are checking the count of it.

In [30]:
for i in df1:
    print(i,"-->",len(df1[i][df1[i] == (-9999.0)]))

datetime_local --> 0
power --> 0
cloud_cover --> 428
apparent_temperature --> 0
temperature --> 0
humidity --> 0
dew_point --> 0
wind_bearing --> 919
wind_speed --> 740
wind_gust --> 3264
pressure --> 2156
uv_index --> 3264
ozone --> 3264
precip_intensity --> 3264
precip_probability --> 3264
precip_type --> 0
visibility --> 176
icon --> 0
summary --> 0

# Considering -9999.0 data as an wrong data imputation we will replace that with mean

In [31]:
numeric = []
category = []
for i in df1 :
    if (df1[i].dtypes=='float64' or df1[i].dtypes=='int64'):
        numeric.append(i)     
    else :
        category.append(i)

In [32]:
for i in numeric:
    df1.replace(-9999.0, np.nan,inplace=True)

In [33]:
df1.isnull().sum()

datetime_local             0
power                      0
cloud_cover              428
apparent_temperature       0
temperature                0
humidity                   0
dew_point                  0
wind_bearing             919
wind_speed               740
wind_gust               3264
pressure                2156
uv_index                3264
ozone                   3264
precip_intensity        3264
precip_probability      3264
precip_type             7129
visibility               176
icon                       0
summary                    0
dtype: int64

In [35]:
mean = ['cloud_cover','wind_speed','wind_gust','uv_index','precip_intensity','precip_probability','visibility','ozone']
fwd = ['wind_bearing','pressure',]

In [36]:
df1 = df1.drop(['precip_type'],axis=1)

In [37]:
for i in df1:
    for j in mean:
        if i==j:
            df1[i].fillna(df1[i].mean(),inplace=True)
        else :
            df1[i].fillna(method='ffill',inplace=True)

# Checking for null values

In [41]:
df1.isnull().sum()

datetime_local          0
power                   0
cloud_cover             0
apparent_temperature    0
temperature             0
humidity                0
dew_point               0
wind_bearing            0
wind_speed              0
wind_gust               0
pressure                0
uv_index                0
ozone                   0
precip_intensity        0
precip_probability      0
visibility              0
icon                    0
summary                 0
dtype: int64

In [44]:
df1.describe()

,power,cloud_cover,apparent_temperature,temperature,humidity,dew_point,wind_bearing,wind_speed,wind_gust,pressure,uv_index,ozone,precip_intensity,precip_probability,visibility
count,13619.000000,13619.000000,13619.000000,13619.000000,13619.000000,13619.000000,13619.000000,13619.000000,13619.000000,13619.000000,13619.000000,13619.000000,13619.000000,13619.000000,13619.000000
mean,35.255627,0.237562,25.944639,24.498054,0.537411,11.924626,190.680667,2.514417,4.245261,1009.952931,1.871270,274.459707,0.058259,0.018400,12.165426
std,557.059759,0.337459,10.469808,8.840016,0.498617,9.129459,110.783674,1.363799,1.898630,7.597269,2.550984,13.295012,0.218980,0.048505,6.268604
min,0.000000,0.000000,3.140000,5.000000,0.000000,-20.560000,0.000000,0.000000,0.630000,991.660000,0.000000,225.800000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,17.310000,17.000000,0.000000,5.920000,92.000000,1.620000,3.015000,1003.450000,0.000000,270.300000,0.000000,0.000000,3.540000
50%,0.000000,0.010000,25.540000,25.000000,1.000000,10.710000,185.000000,2.410000,4.245261,1011.310000,1.000000,274.459707,0.000000,0.000000,16.090000
75%,5.810000,0.410000,34.580000,31.000000,1.000000,19.670000,300.000000,3.330000,4.710000,1016.155000,2.000000,280.800000,0.058259,0.018400,16.090000
max,15504.750000,1.000000,49.750000,47.000000,1.000000,28.350000,359.000000,9.730000,15.150000,1025.690000,12.000000,351.700000,6.220000,0.730000,16.090000

In [46]:
df_label = df1.copy()

In [47]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
df_label['icon'] = labelencoder.fit_transform(df_label['icon'])
df_label['summary'] = labelencoder.fit_transform(df_label['summary'])
df_label

,datetime_local,power,cloud_cover,apparent_temperature,temperature,humidity,dew_point,wind_bearing,wind_speed,wind_gust,pressure,uv_index,ozone,precip_intensity,precip_probability,visibility,icon,summary
0,2017-10-01 00:00:00,0.0,0.00,26.52,26.0,1.0,19.46,308.0,0.83,4.245261,1007.90,1.87127,274.459707,0.058259,0.0184,3.57,1,1
1,2017-10-01 01:00:00,0.0,0.00,28.78,27.0,1.0,20.06,308.0,0.83,4.245261,1007.90,1.87127,274.459707,0.058259,0.0184,3.06,3,2
2,2017-10-01 02:00:00,0.0,0.00,26.58,26.0,1.0,19.97,308.0,0.83,4.245261,1007.90,1.87127,274.459707,0.058259,0.0184,3.06,3,2
3,2017-10-01 03:00:00,0.0,0.00,23.84,23.0,1.0,18.66,270.0,0.45,4.245261,1008.12,1.87127,274.459707,0.058259,0.0184,3.56,1,1
4,2017-10-01 04:00:00,0.0,0.00,24.13,24.0,1.0,17.84,270.0,0.45,4.245261,1008.12,1.87127,274.459707,0.058259,0.0184,3.06,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13614,2019-09-30 19:00:00,0.0,0.16,31.66,29.0,1.0,21.19,40.0,2.72,4.590000,1007.44,0.00000,269.600000,0.000000,0.0000,16.09,5,12
13615,2019-09-30 20:00:00,0.0,0.16,30.42,28.0,1.0,21.35,59.0,3.24,5.450000,1008.25,0.00000,268.700000,0.000000,0.0000,16.09,5,12
13616,2019-09-30 21:00:00,0.0,0.18,29.56,27.0,1.0,21.61,76.0,3.34,5.830000,1008.65,0.00000,268.400000,0.000000,0.0000,16.09,5,12
13617,2019-09-30 22:00:00,0.0,0.30,28.97,27.0,1.0,21.99,88.0,3.22,5.730000,1008.76,0.00000,268.700000,0.000000,0.0000,16.09,5,12
13618,2019-09-30 23:00:00,0.0,0.35,28.15,26.0,1.0,22.09,95.0,3.14,6.030000,1008.61,0.00000,268.700000,0.000000,0.0000,16.09,5,12

In [105]:
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.formula.api as smf
from statsmodels.tools.tools import add_constant

def vif_cal(input_data, dependent_col):
    x_vars=input_data.drop([dependent_col], axis=1)
    xvar_names=x_vars.columns
    for i in range(0, xvar_names.shape[0]):
        y=x_vars[xvar_names[i]] 
        x=x_vars[xvar_names.drop(xvar_names[i])]
        rsq=smf.ols(formula='y~x', data=x_vars).fit().rsquared  
        vif=round(1/(1-rsq),2)
        print( " VIF score for", xvar_names[i], "is -->" , vif)
        
X = df1.copy()
X = X.drop(['datetime_local','icon','summary'], axis = 1)
# calling previously defined function
vif_cal(X,'power')

 VIF score for cloud_cover is --> 1.47
 VIF score for apparent_temperature is --> 42.25
 VIF score for temperature is --> 33.0
 VIF score for humidity is --> 2.73
 VIF score for dew_point is --> 4.02
 VIF score for wind_bearing is --> 1.17
 VIF score for wind_speed is --> 2.65
 VIF score for wind_gust is --> 2.25
 VIF score for pressure is --> 5.62
 VIF score for uv_index is --> 1.4
 VIF score for ozone is --> 1.34
 VIF score for precip_intensity is --> 2.19
 VIF score for precip_probability is --> 2.51
 VIF score for visibility is --> 1.91

## Since ,apparent temperature and temperature had high multivollinearity so removing those columns

In [106]:
df_with =df_label.drop(['apparent_temperature','temperature'],axis=1)

## Using LabelEncoder

In [107]:
df_l =df_with
Q1 = df_l.quantile(0.25)
Q3 = df_l.quantile(0.75)
IQR = Q3 - Q1
print(IQR)

power                  5.81
cloud_cover            0.41
humidity               1.00
dew_point             13.75
wind_bearing         208.00
wind_speed             1.71
wind_gust              1.70
pressure              12.70
uv_index               2.00
ozone                 10.50
precip_intensity       0.06
precip_probability     0.02
visibility            12.55
icon                   2.00
summary                5.00
dtype: float64

In [108]:
df_l1 = df_l[~((df_l < (Q1 - 3 * IQR)) |(df_l > (Q3 + 3 * IQR))).any(axis=1)]
df_l1

,datetime_local,power,cloud_cover,humidity,dew_point,wind_bearing,wind_speed,wind_gust,pressure,uv_index,ozone,precip_intensity,precip_probability,visibility,icon,summary
0,2017-10-01 00:00:00,0.00,0.00,1.00,19.46,308.00,0.83,4.25,1007.90,1.87,274.46,0.06,0.02,3.57,1,1
1,2017-10-01 01:00:00,0.00,0.00,1.00,20.06,308.00,0.83,4.25,1007.90,1.87,274.46,0.06,0.02,3.06,3,2
2,2017-10-01 02:00:00,0.00,0.00,1.00,19.97,308.00,0.83,4.25,1007.90,1.87,274.46,0.06,0.02,3.06,3,2
3,2017-10-01 03:00:00,0.00,0.00,1.00,18.66,270.00,0.45,4.25,1008.12,1.87,274.46,0.06,0.02,3.56,1,1
4,2017-10-01 04:00:00,0.00,0.00,1.00,17.84,270.00,0.45,4.25,1008.12,1.87,274.46,0.06,0.02,3.06,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13614,2019-09-30 19:00:00,0.00,0.16,1.00,21.19,40.00,2.72,4.59,1007.44,0.00,269.60,0.00,0.00,16.09,5,12
13615,2019-09-30 20:00:00,0.00,0.16,1.00,21.35,59.00,3.24,5.45,1008.25,0.00,268.70,0.00,0.00,16.09,5,12
13616,2019-09-30 21:00:00,0.00,0.18,1.00,21.61,76.00,3.34,5.83,1008.65,0.00,268.40,0.00,0.00,16.09,5,12
13617,2019-09-30 22:00:00,0.00,0.30,1.00,21.99,88.00,3.22,5.73,1008.76,0.00,268.70,0.00,0.00,16.09,5,12
13618,2019-09-30 23:00:00,0.00,0.35,1.00,22.09,95.00,3.14,6.03,1008.61,0.00,268.70,0.00,0.00,16.09,5,12

In [141]:
df_l1.set_index(['datetime_local'])
X = df_l1.iloc[:, 2:]
y = df_l1.iloc[:, 1]

In [144]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=50, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
y_pred_train = regressor.predict(X_train)


from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("R score of test data --->",metrics.r2_score(y_test, y_pred))
print("R score of train data--->",metrics.r2_score(y_train, y_pred_train))

Mean Absolute Error: 1.2949536961128425
Mean Squared Error: 5.703331091708171
Root Mean Squared Error: 2.388164795760161
R score of test data ---> 0.7482466615049699
R score of train data---> 0.9615221521783136

## Trying Lazypredict library to get more idea about how the model is performing

In [112]:
from lazypredict.Supervised import LazyRegressor


reg = LazyRegressor(verbose=0,ignore_warnings=True, custom_metric=None)
models,predictions = reg.fit(X_train, X_test, y_train, y_test)
models

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 39/39 [02:02<00:00,  3.15s/it]

                               R-Squared   RMSE  Time Taken
Model
ExtraTreesRegressor                 0.76   2.35        4.03
XGBRegressor                        0.75   2.38        0.78
RandomForestRegressor               0.75   2.39        8.71
LGBMRegressor                       0.74   2.43        0.30
HistGradientBoostingRegressor       0.74   2.45        1.64
BaggingRegressor                    0.72   2.52        0.89
MLPRegressor                        0.68   2.69       24.66
KNeighborsRegressor                 0.68   2.69        0.48
GradientBoostingRegressor           0.68   2.69        3.35
NuSVR                               0.63   2.88        7.01
SVR                                 0.63   2.90        6.01
SGDRegressor                        0.56   3.17        0.07
LinearRegression                    0.56   3.17        0.04
TransformedTargetRegressor          0.56   3.17        0.04
Lars                                0.56   3.17        0.05
Ridge                               0.56   3.17        0.05
RidgeCV                             0.56   3.17        0.06
BayesianRidge                       0.56   3.17        0.04
LassoCV                             0.56   3.17        0.47
LarsCV                              0.56   3.17        0.17
LassoLarsCV                         0.56   3.17        0.19
ElasticNetCV                        0.56   3.17        0.38
LassoLarsIC                         0.55   3.18        0.06
OrthogonalMatchingPursuitCV         0.55   3.21        0.08
AdaBoostRegressor                   0.53   3.25        0.47
DecisionTreeRegressor               0.50   3.35        0.17
ExtraTreeRegressor                  0.50   3.36        0.08
HuberRegressor                      0.48   3.44        0.13
OrthogonalMatchingPursuit           0.47   3.45        0.04
Lasso                               0.42   3.63        0.05
ElasticNet                          0.40   3.69        0.04
LinearSVR                           0.39   3.70        0.81
PassiveAggressiveRegressor          0.30   3.97        0.05
KernelRidge                         0.16   4.36       18.43
DummyRegressor                     -0.00   4.76        0.03
LassoLars                          -0.00   4.76        0.05
GaussianProcessRegressor         -483.34 104.75       42.69

## Now as it seems that the model is working fine so apllying the model on conplete weather_actual data

In [131]:
(df_l1.columns)

Index(['datetime_local', 'power', 'cloud_cover', 'humidity', 'dew_point',
       'wind_bearing', 'wind_speed', 'wind_gust', 'pressure', 'uv_index',
       'ozone', 'precip_intensity', 'precip_probability', 'visibility', 'icon',
       'summary'],
      dtype='object')

In [129]:
test = df_weather_forecast.drop(['plant_id','wind_chill','heat_index','qpf','snow','pop','fctcode','precip_accumulation',
                         'datetime_utc', 'sunrise', 'sunset','updated_at','apparent_temperature','temperature','precip_type','Unnamed: 0'],axis=1)

In [145]:
test = test.set_index(['datetime_local'])
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
test['icon'] = labelencoder.fit_transform(test['icon'])
test['summary'] = labelencoder.fit_transform(test['summary'])
test

,cloud_cover,humidity,dew_point,wind_bearing,wind_speed,wind_gust,pressure,uv_index,ozone,precip_intensity,precip_probability,visibility,icon,summary
datetime_local,,,,,,,,,,,,,,
2019-10-01 00:00:00,0.35,1,22.01,101,3.08,6.42,1008.45,0,268.60,0.00,0.00,16.09,4,4
2019-10-01 01:00:00,0.43,1,22.06,105,2.94,6.28,1008.24,0,269.10,0.00,0.00,16.09,4,4
2019-10-01 02:00:00,0.48,1,22.06,106,2.82,6.08,1007.90,0,269.70,0.00,0.00,16.09,4,4
2019-10-01 03:00:00,0.49,1,21.87,106,2.63,5.74,1007.61,0,270.40,0.00,0.00,16.09,4,4
2019-10-01 04:00:00,0.49,1,21.53,100,2.39,5.30,1007.51,0,271.30,0.00,0.00,16.09,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-10-27 19:00:00,0.00,0,12.20,345,1.74,2.85,1011.70,0,264.90,0.00,0.00,16.09,1,0
2019-10-27 20:00:00,0.00,0,12.06,353,1.39,2.73,1012.28,0,264.90,0.00,0.00,16.09,1,0
2019-10-27 21:00:00,0.00,0,12.19,29,1.15,2.55,1012.67,0,264.60,0.00,0.00,16.09,1,0
2019-10-27 22:00:00,0.00,1,12.50,92,1.03,2.33,1012.79,0,264.30,0.00,0.00,16.09,1,0
2019-10-27 23:00:00,0.00,1,12.67,146,0.91,2.01,1012.85,0,262.80,0.00,0.00,16.09,1,0

In [151]:
X_train = df_l1.iloc[:, 2:]
y_train = df_l1.iloc[:, 1]
X_test = test.iloc[:, 0:]
print(X_train.shape,y_train.shape,X_test.shape)

(11735, 14) (11735,) (648, 14)

In [152]:


# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
y_train = df_l1.iloc[:, 1]

from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=50, random_state=0)
regressor.fit(X_train, y_train)
y_pred_test = regressor.predict(X_test)

test['Output'] = y_pred_test
test

,cloud_cover,humidity,dew_point,wind_bearing,wind_speed,wind_gust,pressure,uv_index,ozone,precip_intensity,precip_probability,visibility,icon,summary,Output
datetime_local,,,,,,,,,,,,,,,
2019-10-01 00:00:00,0.35,1,22.01,101,3.08,6.42,1008.45,0,268.60,0.00,0.00,16.09,4,4,0.67
2019-10-01 01:00:00,0.43,1,22.06,105,2.94,6.28,1008.24,0,269.10,0.00,0.00,16.09,4,4,0.68
2019-10-01 02:00:00,0.48,1,22.06,106,2.82,6.08,1007.90,0,269.70,0.00,0.00,16.09,4,4,0.70
2019-10-01 03:00:00,0.49,1,21.87,106,2.63,5.74,1007.61,0,270.40,0.00,0.00,16.09,4,4,0.93
2019-10-01 04:00:00,0.49,1,21.53,100,2.39,5.30,1007.51,0,271.30,0.00,0.00,16.09,4,4,0.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-10-27 19:00:00,0.00,0,12.20,345,1.74,2.85,1011.70,0,264.90,0.00,0.00,16.09,1,0,0.00
2019-10-27 20:00:00,0.00,0,12.06,353,1.39,2.73,1012.28,0,264.90,0.00,0.00,16.09,1,0,0.00
2019-10-27 21:00:00,0.00,0,12.19,29,1.15,2.55,1012.67,0,264.60,0.00,0.00,16.09,1,0,0.00
2019-10-27 22:00:00,0.00,1,12.50,92,1.03,2.33,1012.79,0,264.30,0.00,0.00,16.09,1,0,0.00
2019-10-27 23:00:00,0.00,1,12.67,146,0.91,2.01,1012.85,0,262.80,0.00,0.00,16.09,1,0,0.00

In [153]:
test.to_csv('Submission_output.csv')

In [154]:
y_pred_train = regressor.predict(X_train)
print("R score of train data--->",metrics.r2_score(y_train, y_pred_train))

R score of train data---> 0.9636861291030345